python train.py \
--trial 401 \
--model pi_lstm \
--target_type ball \
--rloss_weight 1 \
--masking 0.8 \
--bidirectional \
--train_fito \
--valid_fito \
--train_metrica \
--valid_metrica \
--flip_pitch \
--n_players 11 \
--n_features 6 \
--context_dim 128 \
--rnn_dim 256 \
--dropout 0.2 \
--n_epochs 50 \
--start_lr 0.0005 \
--min_lr 1e-5 \
--batch_size 224 \
--print_every_batch 50 \
--save_every_epoch 50 \
--seed 100 \
--cuda